# Site settings
title: GrokCode

email: jess@grokcode.com
description: >
  Grok some code. Programming tutorials, long form articles, and opinion
  pieces about building things on the internet.
about: > # Sidebar about section
  Hi, I'm Jess. I use Python to craft web apps and sift data. I'm currently looking
  for new ways to hone my backend development chops.
intro: > # Main page top text
  Hi, I’m Jess, a developer building delightfully awesome things. You can find
  out more [about me](http://www.grokcode.com/about/), have a look at some [things
  I’ve built](http://www.grokcode.com/programmer-portfolio/), scroll down for my
  latest writing on software development, or browse the [article
  archives](http://www.grokcode.com/category/archives/).<br><br>
  If you are looking for a Full Stack Developer, we should chat. I'm currently
  [looking for my next big thing](http://www.grokcode.com/hire/).
baseurl: "" # the subpath of your site, e.g. /blog/
baseimgurl: "/assets/img/"
url: "http://www.grokcode.com" # the base hostname & protocol for your site
permalink: ':title/'
twitter_username: grokcode
github_username:  grokcode
gplus_id: 104959372961388172986

category_slugs:
  Books &amp; Tools: books-tools
  Tips &amp; Tutorials: tips-tutorials
  Programming Languages: programming-languages
  Career: career
  Extras: extras
  Sweet Hacks: sweet-hacks
  Fun Projects: fun-projects

exclude:
  - README.md
  - Gemfile.lock
  - Gemfile

# Build settings
plugins:
  - jekyll-sitemap
  - jekyll-feed

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge



